version: "3"

services: 
  
  tindev-api:
    build: .
    image: thiagosousa/tindev-spring
    container_name: tindev-api
    ports: 
      - 3333:3333
    depends_on: 
      - mongo
    networks: 
      - tindev
  
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - 27017
    networks: 
      - tindev

networks: 
  tindev:
    driver: bridge

  